// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var NavBulkView = 0;

var AppContainer = 0;

exports.NavBulkView = NavBulkView;
exports.AppContainer = AppContainer;
/* No side effect */
