// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var AppContainer = 0;

var NavBulkView = 0;

exports.AppContainer = AppContainer;
exports.NavBulkView = NavBulkView;
/* No side effect */
