// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as NavItemView$Cockpit from "./NavItemView.bs.js";
import * as NavbarTogglerView$Cockpit from "./NavbarTogglerView.bs.js";
import * as SidebarTogglerView$Cockpit from "./SidebarTogglerView.bs.js";

import ovLogo from './Assets/Overview.svg'
;

import stockLogo from './Assets/Stocks.svg'
;

var ovLogo$prime = (ovLogo);

var stockLogo$prime = (stockLogo);

var component = ReasonReact.statelessComponent("NavbarView");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: "navbar navbar-expand-lg fixed-top",
                          id: "mainNav"
                        }, React.createElement("a", {
                              className: "navbar-brand",
                              href: "#"
                            }, "Logo"), ReasonReact.element(/* None */0, /* None */0, NavbarTogglerView$Cockpit.make(/* array */[])), React.createElement("div", {
                              className: "collapse navbar-collapse",
                              id: "navbarToggler"
                            }, React.createElement("ul", {
                                  className: "navbar-nav navbar-sidenav"
                                }, ReasonReact.element(/* None */0, /* None */0, NavItemView$Cockpit.make("navItemDashboard", "Overview", /* Dashboard */0, React.createElement("img", {
                                              height: "40",
                                              src: ovLogo$prime,
                                              width: "40"
                                            }))), ReasonReact.element(/* None */0, /* None */0, NavItemView$Cockpit.make("navItemStock", "Stocks", /* Stock */1, React.createElement("img", {
                                              height: "40",
                                              src: stockLogo$prime,
                                              width: "40"
                                            })))), ReasonReact.element(/* None */0, /* None */0, SidebarTogglerView$Cockpit.make(/* array */[]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  ovLogo$prime ,
  stockLogo$prime ,
  component ,
  make ,
  
}
/*  Not a pure module */
