// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("SidebarTogglerView");

function handleClick(_, _$1) {
  document.getElementById("doc-page");
  return /* () */0;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("ul", {
                          className: "navbar-nav sidenav-toggler"
                        }, React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: "nav-link text-center",
                                  id: "sidenavToggler",
                                  onClick: Curry._1(self[/* handle */0], handleClick)
                                }, React.createElement("i", {
                                      className: "fa fa-fw fa-angle-left"
                                    }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  handleClick ,
  make ,
  
}
/* component Not a pure module */
