// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as Config$Cockpit from "./Config.bs.js";
import * as Security$Cockpit from "./Security.bs.js";

import axios from 'axios'
;

function transformToCoins(values) {
  return List.map((function (obj) {
                return /* record */[
                        /* amount */obj.amount,
                        /* currency */obj.coinSymbol
                      ];
              }), values);
}

function keycloakQuery(config) {
  return Security$Cockpit.query.then((function (p) {
                var url = config[/* url */0] + ("/sink/resources/users/" + (p.subject + "/coins"));
                var keycloak = {
                  url: url,
                  method: "GET",
                  headers: {
                    Authorization: "Bearer " + p.token
                  }
                };
                return Axios.request(keycloak).then((function (x) {
                              return Promise.resolve(x);
                            }));
              }));
}

function request(c) {
  return Config$Cockpit.read.then(keycloakQuery).then((function (x) {
                    return Promise.resolve($$Array.to_list(x.data));
                  })).then((function (x) {
                  return Promise.resolve(transformToCoins(x));
                })).then((function (x) {
                return Promise.resolve(Curry._1(c, x));
              }));
}

export {
  transformToCoins ,
  keycloakQuery ,
  request ,
  
}
/*  Not a pure module */
