// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";

function transformToCoins(values) {
  return List.map((function (obj) {
                return /* record */[
                        /* amount */obj.amount,
                        /* currency */obj.coinSymbol
                      ];
              }), values);
}

export {
  transformToCoins ,
  
}
/* No side effect */
