// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as Config$Cockpit from "./Config.bs.js";
import * as Security$Cockpit from "./Security.bs.js";

function transformToCoins(values) {
  return List.map((function (obj) {
                return /* record */[
                        /* amount */obj.amount,
                        /* currency */obj.coinSymbol
                      ];
              }), values);
}

function request(c) {
  return Config$Cockpit.read.then((function (x) {
                      return Security$Cockpit.query.then((function (subject) {
                                    return Axios.get(x[/* url */0] + ("/sink/resources/users/" + (subject + "/coins")));
                                  }));
                    })).then((function (x) {
                    return Promise.resolve($$Array.to_list(x.data));
                  })).then((function (x) {
                  return Promise.resolve(transformToCoins(x));
                })).then((function (x) {
                return Promise.resolve(Curry._1(c, x));
              }));
}

export {
  transformToCoins ,
  request ,
  
}
/* axios Not a pure module */
