// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE


import Keycloak from 'keycloak-js'
;

const keycloak = Keycloak()
;

var query = (
  new Promise((resolve, reject) => {
    keycloak.init({
        onLoad: 'login-required'
      }).success(() => resolve({subject: keycloak.subject, token: keycloak.token)).error(error => reject(error))
    })
  );

export {
  query ,
  
}
/*  Not a pure module */
