// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("ContenCoverView");

function make(coins, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var createTd = function (v) {
                return React.createElement("tr", undefined, React.createElement("td", undefined, String(v[/* amount */0])), React.createElement("td", undefined, v[/* currency */1]));
              };
              return React.createElement("div", {
                          className: "content-wrapper"
                        }, React.createElement("div", {
                              className: "container-fluid px-0"
                            }, React.createElement("ol", {
                                  className: "breadcrumb py-3"
                                }, React.createElement("li", {
                                      className: "breadcrumb-item font-weight-bold"
                                    }, React.createElement("h3", undefined, "Dashboard"))), React.createElement("div", {
                                  className: "row ml-0"
                                }, React.createElement("table", undefined, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "Month"), React.createElement("th", undefined, "Savings"))), React.createElement("tbody", undefined, $$Array.of_list(List.map(createTd, coins)))))), React.createElement("footer", {
                              className: "sticky-footer"
                            }, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("div", {
                                      className: "text-center"
                                    }, React.createElement("small", undefined, "Copyright 2018")))), React.createElement("a", {
                              className: "scroll-to-top rounded",
                              href: "#"
                            }, React.createElement("i", {
                                  className: "fa fa-angle-up"
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
