// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

import '../styles/navbulk.css'
;

import _logo from '../images/logo.svg'
;

var logo = (_logo);

var component = ReasonReact.statelessComponent("NavBulkView");

function setSectionRef(theRef, _) {
  if (theRef == null) {
    console.log("Nothing");
    return /* () */0;
  } else {
    console.log(theRef.innerText);
    return /* () */0;
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: "navbar fixed-top navbar-light nav-bulk"
                        }, React.createElement("a", {
                              className: "navbar-brand",
                              href: "#"
                            }, React.createElement("img", {
                                  alt: "",
                                  height: "30",
                                  src: logo,
                                  width: "30"
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  logo ,
  component ,
  setSectionRef ,
  make ,
  
}
/*  Not a pure module */
